### ISSUE TITLE
Source of the original sbml file

### ISSUE THREAD

**Issue by lcottret** [m-jahn/genome-scale-models#13]
Hi !

Please don't forget that the original SBML file has not been produced by Park et al. but by Peyraud et al. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5061431/ ,see supp mat) from the pdf file (!) that Park et al. supplied in their paper...

Regards,

**Comment by m-jahn** [comment]
Thanks for the comment, Ludo. I will add a reference to your paper.
