### ISSUE TITLE
Software to be?

### ISSUE THREAD

**Issue by arianccbasile** [m-jahn/genome-scale-models#14]
Hello :) I really like your resource but I tried to apply it to other models, with minor edits, but it stopped. It seems is a very model-specific resource. Are you planning to make it as a more universal tool? 

Best,
Arianna

**Comment by m-jahn** [comment]
Hi Arianna,

Thanks for your interest in the model. Can you be more specific with the issues you encountered?
This repo contains a genome scale model for Ralstonia eutropha aka Cupriavidus necator. It's a static file in the end - what exactly do you mean by "tried to apply it to other models"? In which way did it stop? Yes this is a model specific resource, it's actually just a the model that you need, ideally.

Maybe you misunderstood that you have to run the python code yourself. This is not necessary, only to recreate the steps to parse and modify the original model from Park et al.
If you want to _work_ with the model, just download it here: 
https://github.com/m-jahn/genome-scale-models/tree/master/Ralstonia_eutropha/sbml

Then follow the steps explained [in the Readme](https://github.com/m-jahn/genome-scale-models#getting-started).

**Comment by arianccbasile** [comment]
I was trying to use this tool on a model I am creating. However, I get this error. Yeah, I understand. I was just trying to adapt to my needs but it is actually not doable. Thank you for answering tho :) 


`Traceback (most recent call last):
  File "/Users/arianna/miniconda3/envs/carveme2/lib/python3.8/site-packages/cobra/core/dictlist.py", line 452, in __getattr__
    return DictList.get_by_id(self, attr)
  File "/Users/arianna/miniconda3/envs/carveme2/lib/python3.8/site-packages/cobra/core/dictlist.py", line 57, in get_by_id
    return list.__getitem__(self, self._dict[id])
KeyError: 'TYRTA1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upgrade_main.py", line 66, in <module>
    main()
  File "upgrade_main.py", line 36, in main
    um.modify_reactions(model)
  File "/Users/arianna/Documents/programs/genome-scale-models-master/Ralstonia_eutropha/upgrade_model.py", line 140, in modify_reactions
    model.reactions.TYRTA1.id = 'TYRTA'
  File "/Users/arianna/miniconda3/envs/carveme2/lib/python3.8/site-packages/cobra/core/dictlist.py", line 454, in __getattr__
    raise AttributeError("DictList has no attribute or entry %s" % attr)
AttributeError: DictList has no attribute or entry TYRTA1
`

**Comment by m-jahn** [comment]
No this is not doable. You might had in mind to update your model with similar code, but this is really highly specific for Ralstonia. Your model probably does not have a reaction called TYRTA1 (and many others), so there's no point to use the code for other models.
