### ISSUE TITLE
GEMs using a homology-based approach (please suggest me how to correct this error)

### ISSUE THREAD

**Issue by glou123** [m-jahn/genome-scale-models#15]
>> sedUnix('CDT1.faa');
>> modelaceto = importModel('RehMBEL1391_sbml_L3V1.xml');
WARNING: The following metabolites are never used in a reaction:
	fol_c

WARNING: The following genes are not associated to a reaction:
	H16_B2371
	H16_A0184
	H16_B1757
	H16_A3290
	H16_A2106

>> modelaceto.mets = regexprep(modelaceto.mets, '\[[a-z]+\]$', '');
>> modelaceto.id = 'aceto';
>> blast = getBlast('aceto1', ['CN.faa'], {'aceto'}, ...
{ 'CDT1.faa'});
BLASTing "aceto" against "aceto1"..
BLASTing "aceto1" against "aceto"..
>> model = getModelFromHomology({modelaceto}, blast, 'aceto1', ...
{'aceto'}, 1, false, 10^-30, 150, 35);
Error using getModelFromHomology (line 145)
Less than 5% of the genes in the template model with model.id
"aceto"
can be found in the blastStructure. Ensure that the protein FASTA
used in getBlast and the template model used in getModelFromHomology
use the same style of gene identifiers

**Comment by m-jahn** [comment]
Sorry but how could I help with this issue? You need to explain what exactly you are trying to achieve, what code you were running, and when and how it failed. In other words provide a reproducible example and some context.
Otherwise I will close this.

**Comment by glou123** [comment]
Hi,

I am trying to follow the script described in published paper titled "Reconstruction of Genome-Scale Metabolic Model for Hansenula polymorpha Using RAVEN". I downloaded published GEM for bacteria (modelaceto) and used it as a template model to build GEM for desired bacteria (aceto1) , I downloaded protein fasta  (for aceto1 its CN.faa  and for aceto its CDT1.faa ) file for both bacteria from NCBI and  sedUnix function wasused  to have same style for gene identifiers. The id for template model was changed from xx to aceto and blast command was run to carry blast for both the fasta files. Finally,  getModelFromHomology command used executed to get model for desired bacteria. So, Error displayed after this command (Error using getModelFromHomology (line 145) Less than 5% of the genes in the template model with model.id "aceto" can be found in the blastStructure. Ensure that the protein FASTA used in getBlast and the template model used in getModelFromHomology use the same style of gene identifiers).
Thanks,
Anjali
Get Outlook for Androi<https://aka.ms/AAb9ysg>d
________________________________

**Comment by m-jahn** [comment]
Hmm you must have misunderstood something. This repo is about Ralstonia, not acetogens. I have not used Raven to make or reconstruct a model from fasta files. And finally, I know nothing about the procedure from the H. polymorpha paper. I suggest you ask your question at the Raven repo or anywhere where the failing function that you use comes from.

**Comment by glou123** [comment]
Thanks
